---

- name: Generating EC2 Keypair
  ec2_key:
    name: "{{ key_name }}"
    region: "{{ aws_region }}"
    state: present
    #key_material: "{{ item }}"
  #with_file: /home/nitin/.ssh/id_rsa.pub
  register: ec2_key

- debug:
    var: ec2_key

- name: Downloading Private Key
  copy: content="{{ ec2_key.key.private_key }}" dest="../files/{{ key_name }}.pem" mode=0600
  when: ec2_key.changed
