---

- name: Setup Public Subnets Route Table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ aws_region }}"
    state: present
    tags:
      Name: "Public-RT-for-{{ vpc_name }}"
    subnets:
      "{{ subnet_ids }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ vpc.igw_id }}"
  register: public_rt

- name: Set up Private Subnets Route Table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ aws_region }}"
    state: present
    tags:
      Name: "Private-RT-for-{{ vpc_name }}"
    subnets:
      "{{ subnet_ids_pvt }}"
    routes:
      - dest: 0.0.0.0/0
        instance_id: "{{ item.instance_id }}"
  with_items: "{{ ec2_nat.instances }}"
  register: private_rt

