---

- name: Allocate a new Elastic IP to NAT Instance
  ec2_eip:
    device_id: "{{ item.instance_id }}"
    region: "{{ aws_region }}"
    state: present
  with_items: "{{ ec2_nat.instances }}"
  register: eip
  when: ec2.changed
  
